[build]
command = "yarn rw build && yarn rw db up --no-db-client --auto-approve && yarn rw dataMigrate up"
publish = "web/dist"
functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/undefined/auth/v1/token?grant_type=password"
  to = "/"
  status = 200

[[redirects]]
  from = "/undefined/auth/v1/signup"
  to = "/"
  status = 200
