# See the full yml reference at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: jobs

# Uncomment org and app if you want to integrate your deployment with the serverless dashboard. See https://www.serverless.com/framework/docs/dashboard/ for more details.
org: dthyresson
app: pyplyn

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    include:
      - DATABASE_URL
      - DIFFBOT_API_BASE_URL
      - DIFFBOT_NLP_API_BASE_URL
      - DIFFBOT_API_TOKEN
      - FEEDLY_BASE_URL
      - FEEDLY_API_TOKEN
      - LOGFLARE_API_KEY
      - LOGFLARE_SOURCE_TOKEN
      - REPEATER_API_KEY
      - FEED_JOB_SECRET
      - FEED_JOB_ENDPOINT
      - DOPPLER_ENVIRONMENT

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2 # This is the AWS region where the service will be deployed.
  httpApi: # HTTP API is used by default. To learn about the available options in API Gateway, see https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html
    cors: true
    payload: '1.0'
  stackTags: # Add CloudFormation stack tags here
    source: serverless
    name: Redwood Lambda API with HTTP API Gateway
  tags: # Add service wide tags here
    name: Redwood Lambda API with HTTP API Gateway

package:
  individually: true

functions:
  entryStream:
    description: entryStream function deployed on AWS Lambda
    package:
      artifact: api/dist/zipball/entryStream.zip # This is the default location of the zip file generated during the deploy command.
    memorySize: 1024 # mb
    timeout: 25 # seconds (max: 29)
    tags: # Tags for this specific lambda function
      endpoint: /.netlify/functions/entryStream
    # Uncomment this section to add environment variables either from the serverless dotenv plugin or using serverless params
    # environment:
    handler: entryStream.handler
    events:
      - httpApi:
          path: /.netlify/functions/entryStream
          method: GET
      - httpApi:
          path: /.netlify/functions/entryStream
          method: POST
  feed:
    description: feed function deployed on AWS Lambda
    package:
      artifact: api/dist/zipball/feed.zip # This is the default location of the zip file generated during the deploy command.
    memorySize: 1024 # mb
    timeout: 25 # seconds (max: 29)
    tags: # Tags for this specific lambda function
      endpoint: /.netlify/functions/feed
    # Uncomment this section to add environment variables either from the serverless dotenv plugin or using serverless params
    # environment:
    handler: feed.handler
    events:
      - httpApi:
          path: /.netlify/functions/feed
          method: GET
      - httpApi:
          path: /.netlify/functions/feed
          method: POST
  test:
    description: feed function deployed on AWS Lambda
    package:
      artifact: api/dist/zipball/test.zip # This is the default location of the zip file generated during the deploy command.
    memorySize: 1024 # mb
    timeout: 25 # seconds (max: 29)
    tags: # Tags for this specific lambda function
      endpoint: /.netlify/functions/test
    # Uncomment this section to add environment variables either from the serverless dotenv plugin or using serverless params
    # environment:
    handler: test.handler
    events:
      - httpApi:
          path: /.netlify/functions/test
          method: GET
      - httpApi:
          path: /.netlify/functions/test
          method: POST
